import { applyDocumentTheme, getInitialTheme } from "../theme.js";
import { bindFitToggleButton } from "../ui/fitToggleButton.ts";
import { icon } from "../ui/icons.ts";
import { siteHeader } from "../ui/siteHeader.ts";
import type {
  AppTheme,
  SelectedRecordDetails,
  VisualizationInstance,
} from "../visualizations/adapter.ts";
import { getVisualizationAdapter } from "../visualizations/adapters.ts";
import {
  comparisonContextFocus,
  loadComparisonSample,
  type LoadedComparisonSample,
} from "../visualizations/comparisonSample.ts";
import { getMethodEvidence, getMethodExportSupport } from "../visualizations/methodEvidence.ts";
import { getMethodPerformance } from "../visualizations/methodPerformance.ts";
import {
  getMethodRatings,
  overallVersatility,
  RATING_CRITERIA,
  SCORE_RUBRIC,
  type RatingCriterionId,
} from "../visualizations/methodRatings.ts";
import {
  getVisualizationMethod,
  VISUALIZATION_METHODS,
  type VisualizationMethodDefinition,
} from "../visualizations/registry.ts";

type SlotId = "a" | "b";
type RatingFilter = "all" | "available" | "in-development";

interface ComparisonState {
  a: string;
  b: string;
  activeMobileSlot: SlotId;
  targetSlot: SlotId;
}

const CATEGORY_LABELS: Readonly<Record<VisualizationMethodDefinition["category"], string>> = {
  primary: "Primary whole-tree method",
  focused: "Focused and familiar",
  graph: "Graph representations",
  research: "Research methods",
  thoroughness: "Included for thoroughness",
};

const COMPARISON_FIT_INSETS = { top: 20, right: 20, bottom: 88, left: 20 } as const;

export class ComparisonApp {
  readonly #root: HTMLElement;
  readonly #sample: LoadedComparisonSample;
  readonly #mobileQuery = window.matchMedia("(max-width: 760px)");
  readonly #views: Record<SlotId, VisualizationInstance | null> = { a: null, b: null };
  readonly #mountGeneration: Record<SlotId, number> = { a: 0, b: 0 };
  #theme: AppTheme = getInitialTheme();
  #state: ComparisonState;
  #ratingFilter: RatingFilter = "all";
  #mobileCriterion: RatingCriterionId | "overall" = "overall";

  private constructor(root: HTMLElement, sample: LoadedComparisonSample) {
    this.#root = root;
    this.#sample = sample;
    this.#state = readStateFromUrl();
  }

  static async start(root: HTMLElement): Promise<ComparisonApp> {
    const sample = await loadComparisonSample();
    const app = new ComparisonApp(root, sample);
    app.#render();
    await app.#reconcileVisibleViews();
    return app;
  }

  #render(): void {
    applyDocumentTheme(this.#theme);
    const projection = this.#sample.projection;
    this.#root.innerHTML = `
      <div class="comparison-page" data-theme="${this.#theme}">
        ${siteHeader({ activePage: "compare", theme: this.#theme })}

        <main>
          <section class="comparison-intro" aria-labelledby="comparison-title">
            <div>
              <p class="comparison-kicker">Live, same-data comparison</p>
              <h1 id="comparison-title">Compare the same family in two views.</h1>
              <p>Choose a method for A and B. Every verified drawing is generated by its Native Visualization from the same real family-tree sample.</p>
            </div>
            <div class="sample-fact" aria-label="Comparison sample">
              ${icon("focus")}
              <span><strong>Avraham</strong> · spouses and descendants · ${projection.descendant_generations} generations</span>
              <small>${formatNumber(projection.people.length)} people · ${formatNumber(projection.families.length)} Families</small>
            </div>
          </section>

          <section id="live-comparison" class="live-comparison" aria-labelledby="live-comparison-title">
            <header class="live-comparison-heading">
              <div>
                <p class="comparison-kicker">A / B workbench</p>
                <h2 id="live-comparison-title">See the methods, then read the tradeoffs.</h2>
              </div>
              <div class="comparison-actions">
                <div class="target-switch" role="group" aria-label="Catalog target">
                  <span>Load methods into</span>
                  <button type="button" data-target-slot="a" aria-pressed="${this.#state.targetSlot === "a"}">A</button>
                  <button type="button" data-target-slot="b" aria-pressed="${this.#state.targetSlot === "b"}">B</button>
                </div>
                <button class="button comparison-swap" type="button">${icon("method")}Swap A / B</button>
              </div>
            </header>

            <div class="mobile-view-tabs" role="tablist" aria-label="Comparison view">
              <button type="button" role="tab" data-mobile-slot="a" aria-selected="${this.#state.activeMobileSlot === "a"}">View A</button>
              <button type="button" role="tab" data-mobile-slot="b" aria-selected="${this.#state.activeMobileSlot === "b"}">View B</button>
            </div>

            <div class="live-comparison-grid" data-active-mobile-slot="${this.#state.activeMobileSlot}">
              ${this.#slotMarkup("a")}
              ${this.#slotMarkup("b")}
            </div>
            <p class="comparison-announcement visually-hidden" role="status" aria-live="polite"></p>
          </section>

          <section id="ratings" class="ratings-section" aria-labelledby="ratings-title">
            <header class="section-heading comparison-section-heading">
              <div>
                <p class="comparison-kicker">Candid capability table</p>
                <h2 id="ratings-title">Stars measure breadth, not a universal winner.</h2>
                <p>Every reviewed score follows the same written rubric. Select any score to read its qualification.</p>
              </div>
              <label class="rating-filter-label">Show
                <select class="rating-filter">
                  <option value="all">All methods</option>
                  <option value="available">Available only</option>
                  <option value="in-development">In development</option>
                </select>
              </label>
            </header>

            <div class="rating-explanation" role="status" aria-live="polite">
              <strong>Select a score</strong><span>Its method-specific reason will appear here.</span>
            </div>

            <div class="desktop-rating-table" tabindex="0" role="region" aria-label="Method capability ratings; scroll sideways for every criterion">
              <table class="rating-table">
                <thead><tr><th scope="col">Method</th>${RATING_CRITERIA.map((criterion) => `<th scope="col" title="${escapeHtml(criterion.description)}">${escapeHtml(criterion.label)}</th>`).join("")}<th scope="col">Overall Versatility</th><th scope="col">Details</th></tr></thead>
                <tbody data-rating-body></tbody>
              </table>
            </div>

            <div class="mobile-ratings">
              <label>Compare one criterion
                <select class="mobile-criterion-select">
                  <option value="overall">Overall Versatility</option>
                  ${RATING_CRITERIA.map((criterion) => `<option value="${criterion.id}">${escapeHtml(criterion.label)}</option>`).join("")}
                </select>
              </label>
              <div class="mobile-rating-list" data-mobile-rating-list></div>
            </div>

            <details class="rubric-details">
              <summary>How the ratings work</summary>
              <div class="rubric-body">
                <div><h3>Score scale</h3><ol>${SCORE_RUBRIC.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ol></div>
                <div><h3>Criteria</h3><dl>${RATING_CRITERIA.map((criterion) => `<div><dt>${escapeHtml(criterion.label)}</dt><dd>${escapeHtml(criterion.description)}</dd></div>`).join("")}</dl></div>
              </div>
            </details>
          </section>

          <section id="method-catalog" class="catalog-section" aria-labelledby="catalog-title">
            <header class="section-heading comparison-section-heading">
              <div><p class="comparison-kicker">All current and future methods</p><h2 id="catalog-title">Available when verified, visible while unfinished.</h2><p>In-development methods have no invented sample or rating. Their intended use and honest limitation remain available in Method Details.</p></div>
            </header>
            <div class="method-catalog">${this.#catalogMarkup()}</div>
          </section>
        </main>

        <footer class="comparison-footer"><a href="/">GeneaQuilt</a><span>Family data and every comparison calculation stay on this device.</span><a href="#live-comparison">Back to A / B</a></footer>
      </div>
    `;
    this.#bindEvents();
    this.#renderRatings();
  }

  #slotMarkup(slot: SlotId): string {
    const methodId = this.#state[slot];
    return `
      <article class="comparison-view" data-comparison-slot="${slot}" aria-label="View ${slot.toUpperCase()}">
        <header class="comparison-view-header">
          <span class="view-letter" aria-hidden="true">${slot.toUpperCase()}</span>
          <label><span>Method</span><select class="comparison-method-select" aria-label="View ${slot.toUpperCase()} method">${methodOptions(methodId)}</select></label>
          <span class="view-count">Preparing…</span>
          <button class="button view-details-button" type="button">Method details ${icon("info")}</button>
        </header>
        <div class="view-focus-line"></div>
        <div class="comparison-viz-shell">
          <div class="comparison-viz-host" data-viz-host></div>
          <aside class="comparison-record-details" hidden></aside>
        </div>
        <div class="comparison-view-controls">
          <div class="view-search-wrap">
            <label class="view-search">${icon("search")}<span class="visually-hidden">Search View ${slot.toUpperCase()}</span><input type="search" autocomplete="off" placeholder="Search visible people" /></label>
            <div class="view-search-results" hidden></div>
          </div>
          <div class="view-zoom" aria-label="View ${slot.toUpperCase()} controls">
            <button class="icon-button view-zoom-out" type="button" aria-label="Zoom out">${icon("minus")}</button>
            <button class="icon-button view-zoom-in" type="button" aria-label="Zoom in">${icon("plus")}</button>
            <button class="button view-fit" type="button" aria-label="Fit View ${slot.toUpperCase()}" aria-pressed="false">${icon("fit")}<span>Fit</span></button>
          </div>
        </div>
        <div class="comparison-view-summary"><p class="view-best"></p><p class="view-limit"></p></div>
      </article>
    `;
  }

  #bindEvents(): void {
    this.#root.querySelector(".site-theme-button")?.addEventListener("click", () => {
      this.#theme = this.#theme === "dark" ? "light" : "dark";
      applyDocumentTheme(this.#theme, { persist: true });
      const page = this.#root.querySelector<HTMLElement>(".comparison-page");
      const button = this.#root.querySelector<HTMLButtonElement>(".site-theme-button");
      if (page) page.dataset.theme = this.#theme;
      if (button) {
        button.ariaLabel = this.#theme === "dark" ? "Use light appearance" : "Use dark appearance";
        button.ariaPressed = String(this.#theme === "dark");
        button.innerHTML = icon(this.#theme === "dark" ? "sun" : "moon");
      }
      for (const view of Object.values(this.#views)) view?.setTheme(this.#theme);
    });
    this.#root.querySelector(".comparison-swap")?.addEventListener("click", () => {
      void this.#swapViews();
    });
    for (const button of this.#root.querySelectorAll<HTMLButtonElement>("[data-target-slot]")) {
      button.addEventListener("click", () => {
        this.#state.targetSlot = button.dataset.targetSlot === "b" ? "b" : "a";
        this.#updateTargetButtons();
        this.#writeUrl();
      });
    }
    for (const button of this.#root.querySelectorAll<HTMLButtonElement>("[data-mobile-slot]")) {
      button.addEventListener("click", () => {
        void this.#setActiveMobileSlot(button.dataset.mobileSlot === "b" ? "b" : "a");
      });
    }
    for (const slot of ["a", "b"] as const) this.#bindSlot(slot);
    this.#root
      .querySelector<HTMLSelectElement>(".rating-filter")
      ?.addEventListener("change", (event) => {
        const value = (event.currentTarget as HTMLSelectElement).value;
        this.#ratingFilter = value === "available" || value === "in-development" ? value : "all";
        this.#renderRatings();
      });
    this.#root
      .querySelector<HTMLSelectElement>(".mobile-criterion-select")
      ?.addEventListener("change", (event) => {
        const value = (event.currentTarget as HTMLSelectElement).value;
        this.#mobileCriterion = value === "overall" ? "overall" : (value as RatingCriterionId);
        this.#renderMobileRatings();
      });
    this.#root.querySelector("[data-rating-body]")?.addEventListener("click", (event) => {
      this.#handleRatingClick(event);
    });
    this.#root.querySelector("[data-mobile-rating-list]")?.addEventListener("click", (event) => {
      this.#handleRatingClick(event);
    });
    this.#root.querySelector(".method-catalog")?.addEventListener("click", (event) => {
      const details = (event.target as HTMLElement).closest<HTMLButtonElement>(
        "[data-catalog-details]",
      );
      if (details?.dataset.catalogDetails) {
        this.#showMethodDetails(details.dataset.catalogDetails);
        return;
      }
      const load = (event.target as HTMLElement).closest<HTMLButtonElement>(
        "[data-catalog-method]",
      );
      if (load?.dataset.catalogMethod) {
        void this.#setMethod(this.#state.targetSlot, load.dataset.catalogMethod, true);
      }
    });
    this.#mobileQuery.addEventListener("change", () => {
      void this.#reconcileVisibleViews();
    });
  }

  #bindSlot(slot: SlotId): void {
    const element = this.#slotElement(slot);
    element
      .querySelector<HTMLSelectElement>(".comparison-method-select")
      ?.addEventListener("change", (event) => {
        void this.#setMethod(slot, (event.currentTarget as HTMLSelectElement).value, true);
      });
    element.querySelector(".view-details-button")?.addEventListener("click", () => {
      this.#showMethodDetails(this.#state[slot]);
    });
    element
      .querySelector(".view-zoom-in")
      ?.addEventListener("click", () => this.#views[slot]?.zoomBy(1.22));
    element
      .querySelector(".view-zoom-out")
      ?.addEventListener("click", () => this.#views[slot]?.zoomBy(0.82));
    const input = element.querySelector<HTMLInputElement>(".view-search input");
    const results = element.querySelector<HTMLElement>(".view-search-results");
    input?.addEventListener("input", () => {
      const matches = this.#views[slot]?.search(input.value) ?? [];
      if (!results) return;
      results.hidden = !input.value.trim();
      results.innerHTML = matches.length
        ? matches
            .slice(0, 10)
            .map(
              (match) =>
                `<button type="button" data-search-record="${escapeHtml(match.id)}"><strong>${escapeHtml(match.label)}</strong><span>${match.kind}</span></button>`,
            )
            .join("")
        : `<p>No matches in this projection.</p>`;
    });
    results?.addEventListener("click", (event) => {
      const button = (event.target as HTMLElement).closest<HTMLButtonElement>(
        "[data-search-record]",
      );
      if (!button?.dataset.searchRecord) return;
      this.#views[slot]?.select(button.dataset.searchRecord, true);
      results.hidden = true;
    });
  }

  async #setMethod(slot: SlotId, methodId: string, announce: boolean): Promise<void> {
    getVisualizationMethod(methodId);
    this.#state[slot] = methodId;
    this.#state.targetSlot = slot;
    this.#writeUrl();
    this.#updateTargetButtons();
    await this.#mountSlot(slot, true);
    if (announce) {
      const status = this.#root.querySelector<HTMLElement>(".comparison-announcement");
      if (status)
        status.textContent = `View ${slot.toUpperCase()} now shows ${getVisualizationMethod(methodId).name}.`;
    }
  }

  async #swapViews(): Promise<void> {
    const previousA = this.#state.a;
    this.#state.a = this.#state.b;
    this.#state.b = previousA;
    this.#writeUrl();
    await Promise.all([this.#mountSlot("a", true), this.#mountSlot("b", true)]);
  }

  async #setActiveMobileSlot(slot: SlotId): Promise<void> {
    this.#state.activeMobileSlot = slot;
    this.#state.targetSlot = slot;
    const grid = this.#root.querySelector<HTMLElement>(".live-comparison-grid");
    if (grid) grid.dataset.activeMobileSlot = slot;
    for (const button of this.#root.querySelectorAll<HTMLButtonElement>("[data-mobile-slot]")) {
      button.setAttribute("aria-selected", String(button.dataset.mobileSlot === slot));
    }
    this.#updateTargetButtons();
    this.#writeUrl();
    await this.#reconcileVisibleViews();
  }

  async #reconcileVisibleViews(): Promise<void> {
    if (this.#mobileQuery.matches) {
      const hidden: SlotId = this.#state.activeMobileSlot === "a" ? "b" : "a";
      this.#destroySlot(hidden);
      await this.#mountSlot(this.#state.activeMobileSlot, false);
      return;
    }
    await Promise.all([this.#mountSlot("a", false), this.#mountSlot("b", false)]);
  }

  async #mountSlot(slot: SlotId, force: boolean): Promise<void> {
    const method = getVisualizationMethod(this.#state[slot]);
    const element = this.#slotElement(slot);
    const select = element.querySelector<HTMLSelectElement>(".comparison-method-select");
    if (select) select.value = method.id;
    this.#renderSlotCopy(slot, method);
    if (this.#mobileQuery.matches && slot !== this.#state.activeMobileSlot) {
      this.#destroySlot(slot);
      return;
    }
    if (!force && this.#views[slot]?.methodId === method.id) return;

    this.#destroySlot(slot);
    const generation = ++this.#mountGeneration[slot];
    const host = element.querySelector<HTMLElement>("[data-viz-host]");
    const count = element.querySelector<HTMLElement>(".view-count");
    if (!host || !count) return;
    const input = element.querySelector<HTMLInputElement>(".view-search input");
    const controls = element.querySelectorAll<HTMLButtonElement>(
      ".view-fit,.view-zoom-in,.view-zoom-out",
    );

    if (method.availability !== "available") {
      host.innerHTML = `<div class="comparison-pending">${icon("method")}<strong>In development</strong><p>No sample or rating is shown until this method passes its mathematical and visual review.</p><button class="button pending-details" type="button">Method details</button></div>`;
      host
        .querySelector(".pending-details")
        ?.addEventListener("click", () => this.#showMethodDetails(method.id));
      count.textContent = "Review pending";
      if (input) {
        input.value = "";
        input.disabled = true;
      }
      controls.forEach((button) => {
        button.disabled = true;
      });
      return;
    }

    count.textContent = "Preparing…";
    host.innerHTML = `<div class="comparison-view-loading">Drawing ${escapeHtml(method.shortName)} locally…</div>`;
    if (input) {
      input.value = "";
      input.disabled = false;
    }
    controls.forEach((button) => {
      button.disabled = false;
    });
    try {
      const focus = comparisonContextFocus(method.id, this.#sample.focuses);
      const view = await getVisualizationAdapter(method.id).mount(host, {
        document: this.#sample.document,
        projection: this.#sample.projection,
        theme: this.#theme,
        fitInsets: COMPARISON_FIT_INSETS,
        ...focus,
        onSelectionChange: (details) => this.#renderRecordDetails(slot, details),
      });
      if (generation !== this.#mountGeneration[slot]) {
        view.destroy();
        return;
      }
      this.#views[slot] = view;
      const fitButton = element.querySelector<HTMLButtonElement>(".view-fit");
      if (fitButton) {
        bindFitToggleButton(fitButton, view, {
          fitLabel: `Fit View ${slot.toUpperCase()}`,
          restoreLabel: `Restore previous View ${slot.toUpperCase()}`,
          fitText: "Fit",
          restoreText: "Restore",
        });
      }
      const summary = view.projectionSummary();
      count.textContent = `${formatNumber(summary.visiblePeople)} visible`;
      count.title = `${summary.label}. ${summary.rule}`;
      if (input) input.placeholder = `Search ${formatNumber(summary.visiblePeople)} visible people`;
      view.fit(false);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      host.innerHTML = `<div class="comparison-pending is-error">${icon("warning")}<strong>This view could not open</strong><p>${escapeHtml(message)}</p></div>`;
      count.textContent = "Could not open";
    }
  }

  #renderSlotCopy(slot: SlotId, method: VisualizationMethodDefinition): void {
    const element = this.#slotElement(slot);
    const best = element.querySelector<HTMLElement>(".view-best");
    const limit = element.querySelector<HTMLElement>(".view-limit");
    const focusLine = element.querySelector<HTMLElement>(".view-focus-line");
    const focus = comparisonContextFocus(method.id, this.#sample.focuses);
    if (best) best.innerHTML = `<strong>Best use</strong>${escapeHtml(method.bestUse)}`;
    if (limit) limit.innerHTML = `<strong>Limit</strong>${escapeHtml(method.limitations)}`;
    if (focusLine) focusLine.textContent = this.#focusLabel(method, focus);
    this.#renderRecordDetails(slot, null);
  }

  #focusLabel(
    method: VisualizationMethodDefinition,
    focus: { focalPersonId?: string; secondaryFocalPersonId?: string },
  ): string {
    if (method.availability !== "available") return "No public sample until review is complete";
    if (
      (method.id === "dual-tree" || method.id === "dual-outline") &&
      focus.focalPersonId &&
      focus.secondaryFocalPersonId
    ) {
      return `Sample axis: ${this.#personName(focus.secondaryFocalPersonId)} → ${this.#personName(focus.focalPersonId)}`;
    }
    if (focus.focalPersonId) return `Sample focus: ${this.#personName(focus.focalPersonId)}`;
    return "Whole Avraham comparison sample";
  }

  #renderRecordDetails(slot: SlotId, details: SelectedRecordDetails | null): void {
    const panel = this.#slotElement(slot).querySelector<HTMLElement>(".comparison-record-details");
    if (!panel) return;
    if (!details) {
      panel.hidden = true;
      panel.replaceChildren();
      return;
    }
    panel.hidden = false;
    panel.innerHTML = `<button class="icon-button record-close" type="button" aria-label="Close details">${icon("close")}</button><span>${details.kind}</span><h3>${escapeHtml(details.label)}</h3>${detailList("Parents", details.parents)}${detailList("Husbands and wives", details.spouses)}${detailList("Children", details.children)}`;
    panel
      .querySelector(".record-close")
      ?.addEventListener("click", () => this.#views[slot]?.clearSelection());
  }

  #renderRatings(): void {
    const methods = this.#filteredMethods();
    const body = this.#root.querySelector<HTMLElement>("[data-rating-body]");
    if (body) body.innerHTML = methods.map((method) => this.#ratingRow(method)).join("");
    this.#renderMobileRatings();
  }

  #ratingRow(method: VisualizationMethodDefinition): string {
    const ratings = getMethodRatings(method.id);
    const methodCell = `<th scope="row"><strong>${escapeHtml(method.shortName)}</strong><span class="availability ${method.availability}">${method.availability === "available" ? "Available" : "In development"}</span></th>`;
    if (!ratings) {
      return `<tr>${methodCell}${RATING_CRITERIA.map(() => `<td class="rating-pending">Review pending</td>`).join("")}<td class="rating-pending">Review pending</td><td><button class="text-button" type="button" data-rating-details="${method.id}">Details</button></td></tr>`;
    }
    const cells = RATING_CRITERIA.map((criterion) =>
      ratingButton(method, criterion.id, ratings[criterion.id].score, ratings[criterion.id].note),
    ).join("");
    const overall = overallVersatility(ratings);
    return `<tr>${methodCell}${cells}<td>${overallButton(method, overall)}</td><td><button class="text-button" type="button" data-rating-details="${method.id}">Details</button></td></tr>`;
  }

  #renderMobileRatings(): void {
    const list = this.#root.querySelector<HTMLElement>("[data-mobile-rating-list]");
    if (!list) return;
    list.innerHTML = this.#filteredMethods()
      .map((method) => {
        const ratings = getMethodRatings(method.id);
        if (!ratings)
          return `<article><div><strong>${escapeHtml(method.shortName)}</strong><span>In development</span></div><em>Review pending</em><button class="text-button" type="button" data-rating-details="${method.id}">Details</button></article>`;
        if (this.#mobileCriterion === "overall") {
          const overall = overallVersatility(ratings);
          return `<article><div><strong>${escapeHtml(method.shortName)}</strong><span>Overall Versatility</span></div>${overallButton(method, overall)}<button class="text-button" type="button" data-rating-details="${method.id}">Details</button></article>`;
        }
        const item = ratings[this.#mobileCriterion];
        return `<article><div><strong>${escapeHtml(method.shortName)}</strong><span>${escapeHtml(RATING_CRITERIA.find((criterion) => criterion.id === this.#mobileCriterion)?.label ?? this.#mobileCriterion)}</span></div>${ratingButtonContent(method, this.#mobileCriterion, item.score, item.note)}<button class="text-button" type="button" data-rating-details="${method.id}">Details</button></article>`;
      })
      .join("");
  }

  #handleRatingClick(event: Event): void {
    const details = (event.target as HTMLElement).closest<HTMLButtonElement>(
      "[data-rating-details]",
    );
    if (details?.dataset.ratingDetails) {
      this.#showMethodDetails(details.dataset.ratingDetails);
      return;
    }
    const button = (event.target as HTMLElement).closest<HTMLButtonElement>("[data-rating-method]");
    if (!button?.dataset.ratingMethod) return;
    const method = getVisualizationMethod(button.dataset.ratingMethod);
    const explanation = this.#root.querySelector<HTMLElement>(".rating-explanation");
    if (!explanation) return;
    const label =
      button.dataset.ratingCriterion === "overall"
        ? "Overall Versatility"
        : (RATING_CRITERIA.find((criterion) => criterion.id === button.dataset.ratingCriterion)
            ?.label ?? "Rating");
    explanation.innerHTML = `<strong>${escapeHtml(method.shortName)} · ${escapeHtml(label)}</strong><span>${escapeHtml(button.dataset.ratingNote ?? "")}</span>`;
  }

  #showMethodDetails(methodId: string): void {
    const method = getVisualizationMethod(methodId);
    const evidence = getMethodEvidence(methodId);
    const ratings = getMethodRatings(methodId);
    const exports = getMethodExportSupport(methodId);
    const performance = getMethodPerformance(methodId);
    const dialog = document.createElement("dialog");
    dialog.className = "comparison-dialog";
    const focus = comparisonContextFocus(method.id, this.#sample.focuses);
    dialog.innerHTML = `<div class="comparison-dialog-body"><button class="icon-button dialog-close" type="button" aria-label="Close">${icon("close")}</button><span class="availability ${method.availability}">${method.availability === "available" ? "Available" : "In development"}</span><h2>${escapeHtml(method.name)}</h2><dl class="dialog-summary"><div><dt>Best use</dt><dd>${escapeHtml(method.bestUse)}</dd></div><div><dt>Limit</dt><dd>${escapeHtml(method.limitations)}</dd></div><div><dt>Sample</dt><dd>${escapeHtml(this.#focusLabel(method, focus))}</dd></div><div><dt>Practical scale</dt><dd>${escapeHtml(method.practicalScale.replace("-", " "))}</dd></div></dl>${evidenceMarkup(evidence)}${performanceMarkup(performance)}${ratingsMarkup(method, ratings)}${exportMarkup(exports)}<div class="dialog-sources"><h3>Research and original work</h3>${method.sources.map((source) => `<a href="${escapeHtml(source.url)}" target="_blank" rel="noreferrer">${escapeHtml(source.label)}</a>`).join("")}</div>${method.availability === "in-development" ? `<p class="dialog-policy">No live sample or stars are published until the implementation passes its accuracy review.</p>` : ""}<div class="dialog-actions"><button class="button button-primary dialog-done" type="button">Done</button></div></div>`;
    const close = (): void => dialog.close();
    dialog.querySelector(".dialog-close")?.addEventListener("click", close);
    dialog.querySelector(".dialog-done")?.addEventListener("click", close);
    dialog.addEventListener("close", () => dialog.remove(), { once: true });
    document.body.append(dialog);
    dialog.showModal();
  }

  #catalogMarkup(): string {
    return Object.entries(CATEGORY_LABELS)
      .map(([category, label]) => {
        const methods = VISUALIZATION_METHODS.filter((method) => method.category === category);
        return `<details ${category === "primary" || category === "focused" ? "open" : ""}><summary><span>${escapeHtml(label)}</span><strong>${methods.length}</strong></summary><div>${methods.map((method) => `<article><div><span class="availability ${method.availability}">${method.availability === "available" ? "Available" : "In development"}</span><h3>${escapeHtml(method.shortName)}</h3><p>${escapeHtml(method.bestUse)}</p><small>${escapeHtml(method.limitations)}</small></div><div><button class="button" type="button" data-catalog-method="${method.id}">Load in ${this.#state.targetSlot.toUpperCase()}</button><button class="text-button" type="button" data-catalog-details="${method.id}">Method details</button></div></article>`).join("")}</div></details>`;
      })
      .join("");
  }

  #filteredMethods(): readonly VisualizationMethodDefinition[] {
    if (this.#ratingFilter === "all") return VISUALIZATION_METHODS;
    return VISUALIZATION_METHODS.filter((method) => method.availability === this.#ratingFilter);
  }

  #updateTargetButtons(): void {
    for (const button of this.#root.querySelectorAll<HTMLButtonElement>("[data-target-slot]")) {
      const selected = button.dataset.targetSlot === this.#state.targetSlot;
      button.setAttribute("aria-pressed", String(selected));
    }
    for (const button of this.#root.querySelectorAll<HTMLButtonElement>("[data-catalog-method]")) {
      button.textContent = `Load in ${this.#state.targetSlot.toUpperCase()}`;
    }
  }

  #destroySlot(slot: SlotId): void {
    this.#mountGeneration[slot] += 1;
    this.#views[slot]?.destroy();
    this.#views[slot] = null;
  }

  #slotElement(slot: SlotId): HTMLElement {
    const element = this.#root.querySelector<HTMLElement>(`[data-comparison-slot="${slot}"]`);
    if (!element) throw new Error(`Comparison View ${slot.toUpperCase()} is missing.`);
    return element;
  }

  #personName(personId: string): string {
    return (
      this.#sample.document.people.find((person) => person.id === personId)?.display_name ??
      personId
    );
  }

  #writeUrl(): void {
    const url = new URL(window.location.href);
    url.searchParams.set("a", this.#state.a);
    url.searchParams.set("b", this.#state.b);
    url.searchParams.set("view", this.#state.activeMobileSlot);
    window.history.replaceState(null, "", `${url.pathname}${url.search}${url.hash}`);
  }
}

function readStateFromUrl(): ComparisonState {
  const query = new URLSearchParams(window.location.search);
  const known = new Set(VISUALIZATION_METHODS.map((method) => method.id));
  const a = query.get("a");
  const b = query.get("b");
  const activeMobileSlot = query.get("view") === "b" ? "b" : "a";
  return {
    a: a && known.has(a) ? a : "geneaquilt",
    b: b && known.has(b) ? b : "bipartite-pgraph",
    activeMobileSlot,
    targetSlot: activeMobileSlot,
  };
}

function methodOptions(selectedId: string): string {
  const available = VISUALIZATION_METHODS.filter((method) => method.availability === "available");
  const unfinished = VISUALIZATION_METHODS.filter(
    (method) => method.availability === "in-development",
  );
  const option = (method: VisualizationMethodDefinition): string =>
    `<option value="${method.id}" ${method.id === selectedId ? "selected" : ""}>${escapeHtml(method.shortName)}</option>`;
  return `<optgroup label="Available">${available.map(option).join("")}</optgroup><optgroup label="In development — review pending">${unfinished.map(option).join("")}</optgroup>`;
}

function ratingButton(
  method: VisualizationMethodDefinition,
  criterionId: RatingCriterionId,
  score: number,
  note: string,
): string {
  return `<td>${ratingButtonContent(method, criterionId, score, note)}</td>`;
}

function ratingButtonContent(
  method: VisualizationMethodDefinition,
  criterionId: RatingCriterionId,
  score: number,
  note: string,
): string {
  return `<button class="rating-button" type="button" data-rating-method="${method.id}" data-rating-criterion="${criterionId}" data-rating-note="${escapeHtml(note)}" aria-label="${escapeHtml(`${method.shortName}: ${score} of 5. ${note}`)}"><span aria-hidden="true">${stars(score)}</span><small>${score}/5</small></button>`;
}

function overallButton(method: VisualizationMethodDefinition, score: number): string {
  const rounded = score.toFixed(1);
  const note =
    "Equal-weight mean of all 17 capability criteria; this measures breadth, not universal quality.";
  return `<button class="rating-button is-overall" type="button" data-rating-method="${method.id}" data-rating-criterion="overall" data-rating-note="${note}" aria-label="${escapeHtml(`${method.shortName}: ${rounded} of 5 Overall Versatility. ${note}`)}"><span aria-hidden="true">${stars(Math.round(score))}</span><small>${rounded}/5</small></button>`;
}

function stars(score: number): string {
  const filled = Math.max(0, Math.min(5, Math.round(score)));
  return `${"★".repeat(filled)}${"☆".repeat(5 - filled)}`;
}

function evidenceMarkup(evidence: ReturnType<typeof getMethodEvidence>): string {
  if (!evidence) return "";
  return `<details class="dialog-disclosure"><summary>${evidence.status === "verified" ? "Accuracy review" : "Review still required"}</summary><div><h3>Checked against</h3><ul>${evidence.checkedAgainst.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul><h3>Invariants</h3><ul>${evidence.invariants.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul><h3>Web version</h3><p>${escapeHtml(evidence.webDifferences)}</p></div></details>`;
}

function performanceMarkup(performance: ReturnType<typeof getMethodPerformance>): string {
  if (!performance) return "";
  const runLabel =
    performance.runs === 1 ? "one measured run" : `median of ${performance.runs} runs`;
  return `<details class="dialog-disclosure"><summary>Measured scale evidence</summary><div><p><strong>${formatNumber(performance.people)}-person deterministic fixture:</strong> ${performance.milliseconds.toFixed(2)} ms for scene construction; ${formatNumber(performance.nodes)} nodes and ${formatNumber(performance.edges)} edges produced.</p><p>${escapeHtml(performance.interpretation)}</p><small>Local Apple M4 Pro / Node 26 baseline, ${runLabel}. Browser paint and interaction are audited separately.</small></div></details>`;
}

function ratingsMarkup(
  method: VisualizationMethodDefinition,
  ratings: ReturnType<typeof getMethodRatings>,
): string {
  if (!ratings) return "";
  return `<details class="dialog-disclosure"><summary>Ratings and qualifications · ${overallVersatility(ratings).toFixed(1)}/5 overall</summary><div class="dialog-rating-list">${RATING_CRITERIA.map((criterion) => `<div><dt>${escapeHtml(criterion.label)}</dt><dd><strong>${ratings[criterion.id].score}/5</strong>${escapeHtml(ratings[criterion.id].note)}</dd></div>`).join("")}</div></details>`;
}

function exportMarkup(exports: ReturnType<typeof getMethodExportSupport>): string {
  if (!exports) return "";
  const entries: Array<[string, boolean]> = [
    ["PNG", exports.png],
    ["Print", exports.print],
    ["Standalone HTML", exports.standaloneHtml],
    ["Current-view PDF", exports.currentViewPdf],
    ["Complete-diagram PDF", exports.completeDiagramPdf],
    ["Tiled Poster PDF", exports.tiledPosterPdf],
  ];
  return `<details class="dialog-disclosure"><summary>Declared export support</summary><div class="dialog-export-list">${entries.map(([label, supported]) => `<span class="${supported ? "is-supported" : "is-pending"}">${supported ? "Yes" : "Not yet"} · ${escapeHtml(label)}</span>`).join("")}</div></details>`;
}

function detailList(label: string, values: string[]): string {
  return values.length
    ? `<div><strong>${escapeHtml(label)}</strong><p>${escapeHtml(values.join(", "))}</p></div>`
    : "";
}

function formatNumber(value: number): string {
  return new Intl.NumberFormat().format(value);
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
